# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klant',
            new_name='Client',
        ),
    ]
