# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0002_auto_20160503_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Achternaam',
            new_name='achternaam',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Voornaam',
            new_name='voornaam',
        ),
    ]
