# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0003_auto_20160519_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='buildingtype',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Half'), ('CL', 'Closed'), ('A', 'Appartment'), ('M', 'Mezzanine'), ('B', 'Bungalow'), ('CA', 'Caravan')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='properties',
            name='heating_type',
            field=models.CharField(choices=[('E', 'Electric'), ('G', 'Gas'), ('F', 'Furnace'), ('H', 'Heat pump'), ('S', 'Special')], default='E', max_length=1),
        ),
    ]
