# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0004_auto_20160519_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
