# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0005_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=30)),
                ('french', models.CharField(max_length=30)),
                ('dutch', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='latitude',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='longitude',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
