# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0006_auto_20160522_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSofiePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', tinymce.models.HTMLField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DisclaimerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', tinymce.models.HTMLField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('visible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', tinymce.models.HTMLField()),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='description',
            new_name='description_dutch',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='extra_information',
            new_name='description_french',
        ),
        migrations.RenameField(
            model_name='properties',
            old_name='title',
            new_name='title_dutch',
        ),
        migrations.AddField(
            model_name='properties',
            name='extra_information_dutch',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='extra_information_french',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='title_french',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
