# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0007_auto_20160523_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 13, 47, 50, 233898, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 13, 48, 13, 585660, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
