# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0007_auto_20160523_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='properties',
            name='latitude',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='properties',
            name='longitude',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
