# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0007_auto_20160523_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='date_created',
            field=models.DateTimeField(default=1984, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='date_modified',
            field=models.DateTimeField(default='1994-08-12', editable=False),
            preserve_default=False,
        ),
    ]
