# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0011_auto_20160531_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='buildingtype',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Half'), ('CL', 'Closed'), ('A', 'Appartment'), ('M', 'Mezzanine'), ('B', 'Bungalow'), ('CA', 'Caravan')], default='O', max_length=2),
        ),
    ]
