# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0012_auto_20160531_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocuments',
            name='path',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypictures',
            name='path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
