# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0013_auto_20160602_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebookrequests',
            options={'verbose_name_plural': 'EbookRequests'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AddField(
            model_name='status',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='status',
            name='eigendom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viaSofie.Properties'),
        ),
        migrations.AlterField(
            model_name='status',
            name='dossierStatus',
            field=models.CharField(choices=[('', ''), ('WB', 'Word Behandeld'), ('C', 'Compromis'), ('F', 'Finale Akte')], default='', max_length=2),
        ),
    ]
