# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0013_auto_20160602_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypictures',
            name='path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
