# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0013_auto_20160602_1210'),
        ('viaSofie', '0014_auto_20160602_1159'),
    ]

    operations = [
    ]
