# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0015_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
    ]
