# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0016_auto_20160602_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'Newsletter'},
        ),
    ]
