# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0017_auto_20160602_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebookrequests',
            options={'verbose_name_plural': 'EbookRequests'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name_plural': 'Propeties'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
