# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0015_aboutpage_language'),
        ('viaSofie', '0018_auto_20160602_1323'),
    ]

    operations = [
    ]
