# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0020_auto_20160603_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sale',
            field=models.BooleanField(default=True),
        ),
    ]
