# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0022_auto_20160603_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'Over ons pagina'},
        ),
    ]
