# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0023_auto_20160603_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSofiePage',
        ),
    ]
