# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0025_auto_20160603_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='busnumber',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
