# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 07:32
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0026_auto_20160606_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=b'')),
                ('priority', models.BooleanField(verbose_name='Kies als hoofdfoto')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ebookrequests',
            options={'verbose_name': 'EbookRequest', 'verbose_name_plural': 'EbookRequests'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq', 'verbose_name_plural': "Faq's"},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Nieuwsbrief', 'verbose_name_plural': 'Nieuwsbrief'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Pand', 'verbose_name_plural': 'Panden'},
        ),
        migrations.AddField(
            model_name='photo',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viaSofie.Properties'),
        ),
    ]
