# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0026_auto_20160603_1344'),
        ('viaSofie', '0026_auto_20160606_0952'),
    ]

    operations = [
    ]
