# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0027_merge'),
        ('viaSofie', '0027_auto_20160612_0732'),
    ]

    operations = [
    ]
