# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0028_auto_20160615_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydocuments',
            name='path',
        ),
        migrations.AddField(
            model_name='propertydocuments',
            name='document',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='propertydocuments',
            name='available',
            field=models.BooleanField(verbose_name='Bestand weergeven'),
        ),
    ]
