# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0028_auto_20160615_1017'),
        ('viaSofie', '0028_merge'),
    ]

    operations = [
    ]
