# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0029_auto_20160615_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocuments',
            name='name',
            field=models.CharField(default='Pand Informatie', max_length=30),
        ),
    ]
