# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0029_merge'),
        ('viaSofie', '0030_propertydocuments_name'),
    ]

    operations = [
    ]
