# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0031_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attic',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viaSofie.Room')),
            ],
            bases=('viaSofie.room',),
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viaSofie.Room')),
            ],
            bases=('viaSofie.room',),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Beschikbaar'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='zichtbaar'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='available',
            field=models.BooleanField(verbose_name='zichtbaar'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Beschikbaar'),
        ),
    ]
