# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0032_auto_20160616_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attic',
            options={'verbose_name': 'Zolder'},
        ),
        migrations.AlterModelOptions(
            name='basement',
            options={'verbose_name': 'Kelder'},
        ),
        migrations.AlterModelOptions(
            name='bathroom',
            options={'verbose_name': 'Badkamer'},
        ),
        migrations.AlterModelOptions(
            name='bedroom',
            options={'verbose_name': 'Slaapkamer'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'Keuken'},
        ),
        migrations.AlterModelOptions(
            name='livingroom',
            options={'verbose_name': 'Woonkamer'},
        ),
        migrations.AlterModelOptions(
            name='storageroom',
            options={'verbose_name': 'Berging', 'verbose_name_plural': 'Bergingen'},
        ),
        migrations.AlterModelOptions(
            name='toilet',
            options={'verbose_name_plural': 'Toiletten'},
        ),
    ]
