# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0033_auto_20160616_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 16, 13, 53, 43, 778053, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
