# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0035_properties_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='remove_the_file',
            field=models.BooleanField(default=False, verbose_name='Verwijder foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='language',
            field=models.CharField(default='NL', max_length=20, verbose_name='taal'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=60, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='bathroom',
            name='bath_type',
            field=models.CharField(max_length=15, verbose_name='type bad'),
        ),
        migrations.AlterField(
            model_name='disclaimerpage',
            name='language',
            field=models.CharField(max_length=20, verbose_name='taal'),
        ),
        migrations.AlterField(
            model_name='disclaimerpage',
            name='title',
            field=models.CharField(max_length=60, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='language',
            field=models.CharField(max_length=3, verbose_name='taal'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.CharField(max_length=20, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='ebookrequests',
            name='ebook_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='viaSofie.Ebook'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='antwoord'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='vraag'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='language',
            field=models.CharField(max_length=20, verbose_name='taal'),
        ),
        migrations.AlterField(
            model_name='privacypage',
            name='title',
            field=models.CharField(max_length=60, verbose_name='titel'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='area',
            field=models.CharField(max_length=10, verbose_name='oppervlakte'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='buildingtype',
            field=models.CharField(choices=[('O', 'Open'), ('H', 'Half'), ('CL', 'Closed'), ('A', 'Appartment'), ('M', 'Mezzanine'), ('B', 'Bungalow'), ('CA', 'Caravan')], default='O', max_length=2, verbose_name='gebouwtype'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='busnumber',
            field=models.CharField(blank=True, max_length=3, verbose_name='busnummer'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(max_length=30, verbose_name='dorp/stad'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='energy_label',
            field=models.CharField(max_length=5, verbose_name='energie label'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='heating_type',
            field=models.CharField(choices=[('E', 'Electric'), ('G', 'Gas'), ('F', 'Furnace'), ('H', 'Heat pump'), ('S', 'Special')], default='E', max_length=1, verbose_name='verwarmingstype'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='housenumber',
            field=models.CharField(max_length=4, verbose_name='huisnummer'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='livingarea',
            field=models.CharField(max_length=10, verbose_name='leef oppervlakte'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='postalcode',
            field=models.CharField(max_length=10, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.CharField(max_length=8, verbose_name='prijs'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='rateable_value',
            field=models.CharField(max_length=8, verbose_name='kadastraal inkomen'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sale',
            field=models.BooleanField(default=True, verbose_name='verkopen'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sold',
            field=models.BooleanField(verbose_name='verkocht'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='street',
            field=models.CharField(max_length=50, verbose_name='straat'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year',
            field=models.CharField(max_length=4, verbose_name='bouwjaar'),
        ),
        migrations.AlterField(
            model_name='room',
            name='area',
            field=models.CharField(max_length=8, verbose_name='oppervlakte'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='busnumber',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Busnummer'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Plaats'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='housenumber',
            field=models.CharField(max_length=4, verbose_name='Huisnummer'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.CharField(max_length=12, verbose_name='Telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='postalcode',
            field=models.CharField(max_length=10, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Straat'),
        ),
    ]
