# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaSofie', '0036_auto_20160621_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocuments',
            name='remove_the_file',
            field=models.BooleanField(default=False, verbose_name='Verwijder foto'),
            preserve_default=False,
        ),
    ]
